# Site settings
title: Rishab Goyal
header-img: img/home-bg.jpg
email: mail@iamrishabgoyal.com
copyright_name: No Copyright
description: "This is Rishab Goyal personal Blog. I am passionately curious about Saleforce and Industry CRM technologies. I belong to Uttrakhand. You can reach to me for any help 
                relating to development or travelling ..."
baseurl: ""
url: "http://iamrishabgoyal.com"
twitter_username: iamrishabgoyal
instagram_username : iamrishabgoyal
github_username:  iamrishabgoyal
facebook_username:  iamrishabgoyal
email_username: mail@iamrishabgoyal.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: jekyll-theme-modernist
